import { Inter } from 'next/font/google'
import './globals.css'
import TopNav from '@/components/TopNav'
import SideNav from '@/components/SideNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<TopNav />
				{/* <div className=' fixed top-[7rem] flex w-[80vw] mx-auto left-[3rem] justify-between'> */}
				<SideNav />
				<div className=' w-[60vw] h-[80vh] pb-[10rem]'>
					<main className={inter.className}>{children}</main>
				</div>
				{/* </div> */}
			</body>
		</html>
	)
}
